CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    balance NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_accounts PRIMARY KEY (id),
    CONSTRAINT chk_accounts_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT chk_accounts_balance_nonnegative CHECK (balance >= 0)
);

CREATE TABLE movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id BIGINT NOT NULL,
    operation_id UUID NOT NULL,
    type VARCHAR(6) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_movements PRIMARY KEY (id),
    CONSTRAINT fk_movements_account FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE RESTRICT,
    CONSTRAINT chk_movements_type CHECK (type IN ('CREDIT', 'DEBIT')),
    CONSTRAINT chk_movements_amount_positive CHECK (amount > 0),
    CONSTRAINT uq_movements_operation_type UNIQUE (operation_id, type)
);

CREATE INDEX idx_movements_account_created_at
    ON movements (account_id, created_at DESC);

CREATE INDEX idx_movements_account_type_created_at
    ON movements (account_id, type, created_at DESC);
